services:
  postgres:
    restart: always
    image: postgres:17-alpine
    environment:
      PGUSER: fabrykapomyslow
      POSTGRES_DB: fabrykapomyslow
      POSTGRES_USER: fabrykapomyslow
      POSTGRES_PASSWORD: fabrykapomyslow_pass
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: